### ISSUE TITLE
Is this usable with a non-custom user model?

### ISSUE THREAD

**Issue by lggwettmann** [salexkidd/django-user-g11n#1]
Great idea and work on this. Is it possible to use this package without a custom-user model? Can it either plug into the standard user model or into a profile-model with a OneToOne-FK to the default user model?

**Comment by salexkidd** [comment]
OK. I reconsider and respect your idea!

**Comment by salexkidd** [comment]
Hi @lggwettmann !

The django-user-g11n does not provide a profile model.

However, your idea is great, so I've made it possible to specify the name to the user profile in settings.py.

Now even users who already use the profile model will be able to use it!

If you like this idea, I'll merge this [PR](https://github.com/salexkidd/django-user-g11n/pull/2
)!

thx

**Comment by salexkidd** [comment]
Ping @lggwettmann  :)

**Comment by lggwettmann** [comment]
Awesome @salexkidd - thanks for that! 🎉

**Comment by salexkidd** [comment]
OK! I'll merge this PR. Thx for reviewing and your great idea! 👍
